version: 2.1
orbs: 
  aws-auth: cardig/aws-auth@1.3.0
executors:
  python_executor:
    docker:
      - image: cimg/python:3.9.13
parameters:
  env_var:
    type: string
    default: "None"
jobs:
  SME_code_review: 
    executor: python_executor
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "92:a6:10:18:dd:37:46:90:aa:f5:0a:ba:36:dd:d8:46"
      - run: echo "SME COde Review"
      - run:
          name: SME_Script
          command: |
            python sme_script.py
            echo "Script run successfully and you can see the status of the  build"
workflows:
  bt_workflow:
    when:
      and:
        - equal: [input, << pipeline.parameters.env_var >>]
    jobs:
      - SME_code_review
    version: 2.1
workflows:
  sandbox_workflow:
    jobs:
      - build:
          context:
            - IIT_SANDBOX_WF
    filters:
      branches:
        only:
          - /feature.*/

      

      
